version: '3.5'
name: order_service

services:
    web.facade:
        container_name: order_webfacade
        image: order_webfacade
        ports:
            - "5029:80"
        build: '../'
        environment:
            ConnectionStrings__DatabaseConnection: 'Data Source=mssql_server; Initial Catalog=OrderService; User ID=SA; Password=Adminadmin1@'
            MenuServiceSettings__Url: 'http://menu_webfacade'
            RedisSettings__Hostname: 'redis'
            GOOGLE_APPLICATION_CREDENTIALS: '/tmp/keys/application_default_credentials.json'
            FirebaseSettings__ProjectId: ''
        networks:
            - app_bridge_network
        volumes:
            - './../application_default_credentials.json:/tmp/keys/application_default_credentials.json:ro'

networks:
    app_bridge_network:
        name: app_bridge_network
        driver: bridge
        external: true